[package]
name = "treest"
version = "0.2.1"
edition = "2021"
description = "Visually explore a file tree."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
dash_conversion = { path = "dash_conversion" }
crossterm = "0.25.0"
dirs = "4.0.0"
glob = "0.3.1"
lazy_static = "1.4.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
signal-hook = "0.3.14"
tui = { version = "0.19.0", features = ["crossterm", "serde"] }
