[package]
name = "treest"
version = "0.1.0"
edition = "2021"

[target."cfg(unix)".dependencies]
libc = "0.2.171"

[target."cfg(windows)".dependencies]
winapi = "0.3.9"

[dependencies]
anyhow = "1.0.97"
dirs = "6.0.0"
lscolors = { version = "0.20.0", default-features = false, features = ["ansi_term"] }
mlua = { version = "0.10.3", features = ["lua54"] }
serde_json = "1.0.140"
serde_yml = "0.0.12"
sqlite = "0.37.0"
sysinfo = { version = "0.34.2", default-features = false, features = ["system"] }
thiserror = "2.0.12"
toml = { version = "0.8.20", default-features = false, features = ["parse"] }
unicode-width = { version = "0.2.0", default-features = false }
xml-rs = "0.8.26"
