.TH TREEST 1 treest-TREEST_VERSION

.SH NAME
treest \- stateful tree view

.SH SYNOPSIS
.B treest
[--printer=\fINAME\fR] [--\fILONGOPTIONS\fR] [-\fIFLAGS\fR] [[--] \fIROOT\fR]

.SH DESCRIPTION
.PP
Print a tree-like representation of a directory to standard output.
Take interactive commands from standard input.
When supported and standard output is a TTY, it is set to raw mode.

.SH OPTIONS
.TP
\fB\-\-help
Show the quick help.
Must be the only argument.
.TP
\fB\-\-version
Print the version successfully.
Must be the only argument.
.TP
\fB\-\-printer=\fINAME\fR
Use the specified printer.
.TP
\fB\-\-\fILONGOPTIONS\fR
Other options are forwarded to the last specified printer.

.SH PRINTERS
.PP
The flags available depend on the printer used.
Unknown flags are silently ignored.
The default printer is "\fBascii\fR"
.TP
\fBascii\fR
blablabla
.TP
\fBfancy\fR
blablabla

.SH COMMANDS
.PP
The following commands should be available.
Note that from any prompt or pending state, \fB'^['\fR (\fBESC\fR) should bring it back to "normal mode".
blablabla

.SH AUTHOR
Grenier Celestin
