.TH TREEST 1 treest-0.0.2

.SH NAME
treest \- stateful tree view

.SH SYNOPSIS
.B treest
[--printer=\fINAME\fR] [-\fIFLAGS\fR] [[--] \fIROOT\fR]

.SH DESCRIPTION
.PP
Print a tree-like representation of a directory to standard output.
Take interactive commands from standard input.

.SH OPTIONS
.TP
\fB\-h, \-\-help
Show the quick help.
.TP
\fB\-\-version
Print the version successfully.
.TP
\fB\-\-printer=\fINAME\fR
Use the specified printer.

.SH PRINTERS
.PP
The flags available depend on the printer used.
Unknown flags are silently ignored.
The default printer is "\fBascii\fR"
.TP
\fBascii\fR
blablabla
.TP
\fBfancy\fR
blablabla

.SH COMMANDS
.PP
The following commands are always available.
Note that from any prompt or pending state, \fB'^['\fR (\fBESC\fR) should bring it back to normal mode.
blablabla

.SH AUTHOR
Grenier Celestin
