use std::cmp::Ordering;

use anyhow::Result;

use crate::tree::{Fragment, NodePath};

/// when an event is generated by eg the provider's poller,
/// it will be an `Event`; it is then translated
/// into an `Notif<&'_>` and notified back
#[derive(Debug)]
pub struct Event {
    pub path: Vec<Fragment>,
    pub kind: EventKind,
}
#[derive(Debug)]
pub enum EventKind {
    /// create (brand new node, folded and not loaded)
    Create(Fragment),
    /// modify (only the node itself, stays loaded if it was, no re-loading, may have a from-to)
    Modify(Option<Vec<Fragment>>, Option<Fragment>),
    /// remove
    Remove,
    /// reload (remove for each contained, re-load may be lazily
    ///         ie same -but not quite- as remove + create + loading if it was
    ///         ie same -but not quite- as remove each + create each)
    Reload,
}
pub type EventPoller = Box<dyn Fn() -> Event>;

/// a notif is _somewhat_ a borrowed event
#[derive(Debug)]
pub struct Notif<'a> {
    pub path: &'a NodePath<'a>,
    pub kind: NotifKind<'a>,
}
#[derive(Debug)]
pub enum NotifKind<'a> {
    /// create (brand new node, folded and not loaded)
    Create(&'a Fragment),
    /// modify (only the node itself, stays loaded if it was, no re-loading, may have a from-to)
    Modify(Option<&'a NodePath<'a>>, Option<&'a Fragment>),
    /// remove
    Remove,
    /// reload (remove for each contained, re-load may be lazily
    ///         ie same -but not quite- as remove + create + loading if it was
    ///         ie same -but not quite- as remove each + create each)
    Reload,
}

/// A type that is able to provide a tree structure.
pub trait Provider: Send {
    fn provide_root(&self) -> Fragment;
    fn provide(&mut self, path: &NodePath) -> Vec<Fragment>;

    fn order(&self, left: &NodePath, right: &NodePath) -> Ordering;
    fn keep(&self, path: &NodePath) -> bool;

    /// display of a single node at path
    /// may be sgr stylized and decorated
    fn display(&self, path: &NodePath) -> String;
    /// each must be plain and undecorated
    fn components(&self, path: &NodePath) -> Vec<String>;
    /// essentially an undecorated, non sgr stylized, no additional text version of breadcrumbs
    fn join(&self, components: &[String]) -> String;

    /// i need dat to translate an event into a notif
    /// most of the time it's literaly just Eq, but providers
    /// like fs that also use fragment to store extra meta
    /// cant just use Eq 'cause not obj safe
    fn compare(&self, in_tree: &Fragment, in_event: &Fragment) -> bool;

    /// the default impl calls `display` for each components and joins with ""
    /// may be overridden to have additional text and sgr styling
    fn breadcrumbs(&self, path: &NodePath) -> String {
        let r: String = (0..path.head.len())
            .map(|k| self.display(&path.head[..=k].into()))
            .collect();
        r + &self.display(path)
    }

    /// returns a blocking function
    fn event_poller(&mut self) -> Option<EventPoller> {
        None
    }
    /// is notified of an event its event poller emitted
    /// event may also be caused by a request
    /// mainly as an occasion to update said poller
    fn event_occured(&mut self, event: &Event, notif: &Notif) {
        _ = (event, notif);
    }

    /// Request to create a new node at `path`.
    /// `text` comes from user input and its interpretation is provider-dependent.
    fn request_mk(&mut self, path: &NodePath, text: String) -> Result<Option<Event>> {
        _ = (path, text);
        Ok(None)
    }
    /// Request to copy an existing node at `path`.
    /// `text` comes from user input and its interpretation is provider-dependent.
    fn request_cp(&mut self, path: &NodePath, text: String) -> Result<Option<Event>> {
        _ = (path, text);
        Ok(None)
    }
    /// Request to remove an existing node at `path`.
    fn request_rm(&mut self, path: &NodePath) -> Result<Option<Event>> {
        _ = (path,);
        Ok(None)
    }
    /// Request to move an existing node at `path`.
    /// `text` comes from user input and its interpretation is provider-dependent.
    /// The default implementation uses `request_cp` and `request_rm` which might be undesirable.
    fn request_mv(&mut self, path: &NodePath, text: String) -> Result<Option<Event>> {
        self.request_cp(path, text)?;
        self.request_rm(path)?;
        Ok(None)
    }
    /// Request to "change" an existing node at `path`.
    /// The meaning is provider- and input- dependent.
    /// `text` comes from user input and its interpretation is provider-dependent.
    fn request_ch(&mut self, path: &NodePath, text: String) -> Result<Option<Event>> {
        _ = (path, text);
        Ok(None)
    }
    /// Request to visualise more content / information about an existing node at `path`.
    fn request_vi(&mut self, path: &NodePath) -> Result<Vec<String>> {
        _ = (path,);
        Ok(Vec::new())
    }
    /// Arbitrary provider request extension. `path` may or may not be relevant.
    /// `text` comes from user input and its interpretation is provider-dependent.
    fn request_ex(
        &mut self,
        path: &NodePath,
        text: String,
    ) -> Result<(Vec<String>, Option<Event>)> {
        _ = (path, text);
        Ok((Vec::new(), None))
    }
}

macro_rules! providers {
    ($($nm:ident::$ty:ident),+$(,)?) => {
        $(pub mod $nm;)+

        pub const NAMES: &'static [&'static str] = &[$(stringify!($nm),)+];

        pub fn guess(arg: &str) -> Option<&'static str> {
            $(if $nm::$ty::guess(arg) {
                return Some(stringify!($nm));
            })+
            None
        }

        pub fn select(arg: &str, name: &str) -> Result<Box<dyn Provider>> {
            match name {
                $(stringify!($nm) => $nm::$ty::new(arg).map(|p| {
                    let p: Box<dyn Provider> = Box::new(p);
                    p
                }),)+
                _ => unreachable!(),
            }
        }
    }
}

providers! {
    fs::Fs,
    scratch::Scratch,
}
// lua::structs::ProviderFlags is updated manually...
